### ISSUE TITLE
chore(spec): Clean up zone errors in karma tests

### ISSUE THREAD

**Issue by d3viant0ne** [DeviantJS/angular2-seed-material2#29]
`Chrome 50.0.2661 (Mac OS X 10.11.5) ERROR: 'Unhandled Promise rejection:', 'By is not defined', '; Zone:', '<root>', '; Task:', 'Promise.then', '; Value:', ReferenceError{}`

Clean up this stuff

**Comment by JanStureNielsen** [comment]
With `npm test` I see the following, possibly related, exception:

```
ERROR: 'Unhandled Promise rejection:', 'EXCEPTION: Error in http://localhost:9876/base/dist/dev/app/+home/home.component.js class HomeComponent - inline template:11:22
ORIGINAL EXCEPTION: No value accessor for ''
ORIGINAL STACKTRACE:
Error: No value accessor for ''
    at new BaseException (http://localhost:9876/base/node_modules/@angular/common/src/facade/exceptions.js:27:23)
    at _throwError (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/shared.js:55:11)
    at Object.setUpControl (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/shared.js:30:9)
    at NgModel.ngOnChanges (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/ng_model.js:41:22)
    at DebugAppView._View_HomeComponent0.detectChangesInternal (HomeComponent.template.js:258:48)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at ViewRef_.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view_ref.js:131:65)
    at ComponentFixture._tick (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:63:32)
    at eval (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:49)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Object.onInvoke (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:53:41)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:322:35)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at NgZoneImpl.runInner (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:84:71)
    at NgZone.run (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone.js:235:66)
    at ComponentFixture.detectChanges (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:25)
    at eval (http://localhost:9876/base/dist/dev/app/+home/home.component.spec.js:27:24)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:571:58
    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:356:38)
    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:256:48)
    at drainMicroTaskQueue (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:474:36)
```
