### ISSUE TITLE
ERROR: 'Unhandled Promise rejection:' @ home.component.js - inline template:11:22

### ISSUE THREAD

**Issue by JanStureNielsen** [DeviantJS/angular2-seed-material2#37]
After `npm install`, an `npm test` results in the following exception:

```
START:
05 07 2016 10:00:20.033:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
05 07 2016 10:00:20.038:INFO [launcher]: Starting browser Chrome
05 07 2016 10:00:22.250:INFO [Chrome 51.0.2704 (Linux 0.0.0)]: Connected on socket /#FM44NJNidkxpAdZTAAAA with id 71421747
Chrome 51.0.2704 (Linux 0.0.0) ERROR: Error{originalErr: SyntaxError{}}
  About component
    ✔ should work
  NameList Service
    ✔ should return an Observable when get called
    ✔ should resolve to list of names when get called
WARN: '
      *It looks like you're using the old forms module. This will be opt-in in the next RC, and
      will eventually be removed in favor of the new forms module. For more information, see:
      https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub
    '
ERROR: 'Unhandled Promise rejection:', 'EXCEPTION: Error in http://localhost:9876/base/dist/dev/app/+home/home.component.js class HomeComponent - inline template:11:22
ORIGINAL EXCEPTION: No value accessor for ''
ORIGINAL STACKTRACE:
Error: No value accessor for ''
    at new BaseException (http://localhost:9876/base/node_modules/@angular/common/src/facade/exceptions.js:27:23)
    at _throwError (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/shared.js:55:11)
    at Object.setUpControl (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/shared.js:30:9)
    at NgModel.ngOnChanges (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/ng_model.js:41:22)
    at DebugAppView._View_HomeComponent0.detectChangesInternal (HomeComponent.template.js:258:48)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at ViewRef_.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view_ref.js:131:65)
    at ComponentFixture._tick (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:63:32)
    at eval (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:49)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Object.onInvoke (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:53:41)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:322:35)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at NgZoneImpl.runInner (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:84:71)
    at NgZone.run (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone.js:235:66)
    at ComponentFixture.detectChanges (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:25)
    at eval (http://localhost:9876/base/dist/dev/app/+home/home.component.spec.js:27:24)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:571:58
    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:356:38)
    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:256:48)
    at drainMicroTaskQueue (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:474:36)
ERROR CONTEXT:
[object Object]', '; Zone:', '<root>', '; Task:', 'Promise.then', '; Value:', ViewWrappedException{_wrapperMessage: 'Error in http://localhost:9876/base/dist/dev/app/+home/home.component.js class HomeComponent - inline template:11:22', _originalException: BaseException{message: 'No value accessor for ''', stack: 'Error: No value accessor for ''
    at new BaseException (http://localhost:9876/base/node_modules/@angular/common/src/facade/exceptions.js:27:23)
    at _throwError (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/shared.js:55:11)
    at Object.setUpControl (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/shared.js:30:9)
    at NgModel.ngOnChanges (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/ng_model.js:41:22)
    at DebugAppView._View_HomeComponent0.detectChangesInternal (HomeComponent.template.js:258:48)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at ViewRef_.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view_ref.js:131:65)
    at ComponentFixture._tick (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:63:32)
    at eval (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:49)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Object.onInvoke (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:53:41)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:322:35)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at NgZoneImpl.runInner (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:84:71)
    at NgZone.run (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone.js:235:66)
    at ComponentFixture.detectChanges (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:25)
    at eval (http://localhost:9876/base/dist/dev/app/+home/home.component.spec.js:27:24)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:571:58
    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:356:38)
    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:256:48)
    at drainMicroTaskQueue (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:474:36)'}, _originalStack: 'Error: No value accessor for ''
    at new BaseException (http://localhost:9876/base/node_modules/@angular/common/src/facade/exceptions.js:27:23)
    at _throwError (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/shared.js:55:11)
    at Object.setUpControl (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/shared.js:30:9)
    at NgModel.ngOnChanges (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/ng_model.js:41:22)
    at DebugAppView._View_HomeComponent0.detectChangesInternal (HomeComponent.template.js:258:48)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at ViewRef_.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view_ref.js:131:65)
    at ComponentFixture._tick (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:63:32)
    at eval (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:49)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Object.onInvoke (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:53:41)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:322:35)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at NgZoneImpl.runInner (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:84:71)
    at NgZone.run (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone.js:235:66)
    at ComponentFixture.detectChanges (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:25)
    at eval (http://localhost:9876/base/dist/dev/app/+home/home.component.spec.js:27:24)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:571:58
    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:356:38)
    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:256:48)
    at drainMicroTaskQueue (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:474:36)', _context: DebugContext{_view: DebugAppView{clazz: ..., componentType: ..., type: ..., viewUtils: ..., parentInjector: ..., declarationAppElement: ..., cdMode: ..., contentChildren: ..., viewChildren: ..., viewContainerElement: ..., numberOfChecks: ..., activeAnimationPlayers: ..., ref: ..., renderer: ..., staticNodeDebugInfos: ..., _currentDebugContext: ..., context: ..., _hasExternalHostElement: ..., projectableNodes: ..., _text_0: ..., _el_1: ..., _text_2: ..., _el_3: ..., _text_4: ..., _text_5: ..., _el_6: ..., _text_7: ..., _text_8: ..., _el_9: ..., _appEl_9: ..., _MdCard_9_4: ..., _text_10: ..., _el_11: ..., _NgForm_11_3: ..., _text_12: ..., _el_13: ..., _text_14: ..., _el_15: ..., _appEl_15: ..., _NgModel_15_4: ..., _NgControl_15_5: ..., _NgControlStatus_15_6: ..., _MdInput_15_7: ..., _query_MdPlaceholder_15_0: ..., _query_MdHint_15_1: ..., _text_16: ..., _el_17: ..., _appEl_17: ..., _MdButton_17_4: ..., _text_18: ..., _text_19: ..., _text_20: ..., _text_21: ..., _el_22: ..., _appEl_22: ..., _MdList_22_4: ..., _text_23: ..., _anchor_24: ..., _appEl_24: ..., _TemplateRef_24_5: ..., _NgFor_24_6: ..., _text_25: ..., _text_26: ..., _text_27: ..., _text_28: ..., _expr_4: ..., _expr_5: ..., _expr_6: ..., _expr_7: ..., _expr_8: ..., _expr_9: ..., _expr_10: ..., _expr_11: ..., _expr_12: ..., _expr_13: ..., _expr_17: ..., _expr_18: ..., _expr_19: ..., _pipe_async_0: ..., rootNodesOrAppElements: ..., allNodes: ..., disposables: ..., subscriptions: ...}, _nodeIndex: 15, _tplRow: 11, _tplCol: 22}, _wrapperStack: 'Error: Error in http://localhost:9876/base/dist/dev/app/+home/home.component.js class HomeComponent - inline template:11:22
    at ViewWrappedException.WrappedException [as constructor] (http://localhost:9876/base/node_modules/@angular/core/src/facade/exceptions.js:45:31)
    at new ViewWrappedException (http://localhost:9876/base/node_modules/@angular/core/src/linker/exceptions.js:68:16)
    at DebugAppView._rethrowWithContext (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:365:23)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:351:18)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at ViewRef_.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view_ref.js:131:65)
    at ComponentFixture._tick (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:63:32)
    at eval (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:49)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Object.onInvoke (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:53:41)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:322:35)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at NgZoneImpl.runInner (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:84:71)
    at NgZone.run (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone.js:235:66)
    at ComponentFixture.detectChanges (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:25)
    at eval (http://localhost:9876/base/dist/dev/app/+home/home.component.spec.js:27:24)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:571:58
    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:356:38)
    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:256:48)
    at drainMicroTaskQueue (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:474:36)'}
ERROR: Error{rejection: ViewWrappedException{_wrapperMessage: 'Error in http://localhost:9876/base/dist/dev/app/+home/home.component.js class HomeComponent - inline template:11:22', _originalException: BaseException{message: ..., stack: ...}, _originalStack: 'Error: No value accessor for ''
    at new BaseException (http://localhost:9876/base/node_modules/@angular/common/src/facade/exceptions.js:27:23)
    at _throwError (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/shared.js:55:11)
    at Object.setUpControl (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/shared.js:30:9)
    at NgModel.ngOnChanges (http://localhost:9876/base/node_modules/@angular/common/src/forms-deprecated/directives/ng_model.js:41:22)
    at DebugAppView._View_HomeComponent0.detectChangesInternal (HomeComponent.template.js:258:48)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at ViewRef_.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view_ref.js:131:65)
    at ComponentFixture._tick (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:63:32)
    at eval (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:49)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Object.onInvoke (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:53:41)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:322:35)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at NgZoneImpl.runInner (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:84:71)
    at NgZone.run (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone.js:235:66)
    at ComponentFixture.detectChanges (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:25)
    at eval (http://localhost:9876/base/dist/dev/app/+home/home.component.spec.js:27:24)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:571:58
    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:356:38)
    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:256:48)
    at drainMicroTaskQueue (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:474:36)', _context: DebugContext{_view: ..., _nodeIndex: ..., _tplRow: ..., _tplCol: ...}, _wrapperStack: 'Error: Error in http://localhost:9876/base/dist/dev/app/+home/home.component.js class HomeComponent - inline template:11:22
    at ViewWrappedException.WrappedException [as constructor] (http://localhost:9876/base/node_modules/@angular/core/src/facade/exceptions.js:45:31)
    at new ViewWrappedException (http://localhost:9876/base/node_modules/@angular/core/src/linker/exceptions.js:68:16)
    at DebugAppView._rethrowWithContext (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:365:23)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:351:18)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:254:14)
    at DebugAppView.AppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view.js:348:44)
    at ViewRef_.detectChanges (http://localhost:9876/base/node_modules/@angular/core/src/linker/view_ref.js:131:65)
    at ComponentFixture._tick (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:63:32)
    at eval (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:49)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Object.onInvoke (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:53:41)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:322:35)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at NgZoneImpl.runInner (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone_impl.js:84:71)
    at NgZone.run (http://localhost:9876/base/node_modules/@angular/core/src/zone/ng_zone.js:235:66)
    at ComponentFixture.detectChanges (http://localhost:9876/base/node_modules/@angular/core/testing/component_fixture.js:77:25)
    at eval (http://localhost:9876/base/dist/dev/app/+home/home.component.spec.js:27:24)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:571:58
    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:356:38)
    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:256:48)
    at drainMicroTaskQueue (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:474:36)'}, promise: ZoneAwarePromise{__zone_symbol__state: 0, __zone_symbol__value: ViewWrappedException{_wrapperMessage: ..., _originalException: ..., _originalStack: ..., _context: ..., _wrapperStack: ...}}, zone: Zone{_properties: Object{}, _parent: null, _name: '<root>', _zoneDelegate: ZoneDelegate{_taskCounts: ..., zone: ..., _parentDelegate: ..., _forkZS: ..., _forkDlgt: ..., _interceptZS: ..., _interceptDlgt: ..., _invokeZS: ..., _invokeDlgt: ..., _handleErrorZS: ..., _handleErrorDlgt: ..., _scheduleTaskZS: ..., _scheduleTaskDlgt: ..., _invokeTaskZS: ..., _invokeTaskDlgt: ..., _cancelTaskZS: ..., _cancelTaskDlgt: ..., _hasTaskZS: ..., _hasTaskDlgt: ...}}, task: ZoneTask{runCount: 1, type: 'microTask', zone: Zone{_properties: ..., _parent: ..., _name: ..., _zoneDelegate: ...}, source: 'Promise.then', data: undefined, scheduleFn: undefined, cancelFn: null, callback: function () { ... }, invoke: function () { ... }}}
  Home component
    ✔ should work

Finished in 0.26 secs / 0.439 secs

SUMMARY:
✔ 4 tests completed

=============================== Coverage summary ===============================
Statements   : 85.37% ( 140/164 )
Branches     : 55.32% ( 104/188 )
Functions    : 75.76% ( 25/33 )
Lines        : 88.64% ( 117/132 )
================================================================================
```

**Comment by JanStureNielsen** [comment]
@d3viant0ne - is this might be a duplicate of #29?

**Comment by d3viant0ne** [comment]
Yeah, it's the long version of the error in #29

PR fixing the tests will be in shortly.
