### ISSUE TITLE
(index):49 Error: TypeError: core_2.BooleanFieldValue is not a function(…)

### ISSUE THREAD

**Issue by clp334264003** [DeviantJS/angular2-seed-material2#56]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.
(index):49 Error: TypeError: core_2.BooleanFieldValue is not a function(…)

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by clp334264003** [comment]
(index):49 Error: TypeError: core_2.BooleanFieldValue is not a function
	    at eval (http://localhost:5555/node_modules/@angular2-material/button-toggle/button-toggle.js:197:20)
	    at Object.eval (http://localhost:5555/node_modules/@angular2-material/button-toggle/button-toggle.js:219:6)
	    at Object.eval (http://localhost:5555/app/shared/material.module.js:12:23)
	    at eval (http://localhost:5555/app/shared/material.module.js:89:4)
	    at eval (http://localhost:5555/app/shared/material.module.js:90:3)
	Evaluating http://localhost:5555/app/shared/material.module.js
	Evaluating http://localhost:5555/app/shared/shared.module.js
	Evaluating http://localhost:5555/app/home/home.module.js
	Evaluating http://localhost:5555/app/app.module.js
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js "Report this error at https://github.com/mgechev/angular2-seed/issues"

**Comment by JohnnyQQQQ** [comment]
This is not enough information. Please follow the issue template.
