### ISSUE TITLE
Running npm run build.prod.exp throws error

### ISSUE THREAD

**Issue by naveedahmed1** [DeviantJS/angular2-seed-material2#65]
When I try to run it with AoT compilation i.e. through command npm run build.prod.exp it throws below errors:

```
[03:05:15] Starting 'compile.ahead.prod'...
Error: Error at D:/angular2-seed/typings/globals/hammerjs/index.d.ts:6:5: Duplicate identifier 'export='.
Error at D:/angular2-seed/typings/globals/hammerjs/index.d.ts:68:6: Duplicate identifier 'RecognizerTuple'.
Error at D:/angular2-seed/typings/globals/hammerjs/index.d.ts:136:15: Duplicate identifier 'HammerInput'.
Error at D:/angular2-seed/typings/globals/hammerjs/index.d.ts:214:15: Duplicate identifier 'MouseInput'.
Error at D:/angular2-seed/typings/globals/hammerjs/index.d.ts:219:15: Duplicate identifier 'PointerEventInput'.
Error at D:/angular2-seed/typings/globals/hammerjs/index.d.ts:224:15: Duplicate identifier 'SingleTouchInput'.
Error at D:/angular2-seed/typings/globals/hammerjs/index.d.ts:229:15: Duplicate identifier 'TouchInput'.
Error at D:/angular2-seed/typings/globals/hammerjs/index.d.ts:234:15: Duplicate identifier 'TouchMouseInput'.
Error at D:/angular2-seed/typings/globals/hammerjs/index.d.ts:346:15: Duplicate identifier 'TouchAction'.
Error at D:/angular2-seed/node_modules/@types/hammerjs/index.d.ts:9:5: Duplicate identifier 'export='.
Error at D:/angular2-seed/node_modules/@types/hammerjs/index.d.ts:71:6: Duplicate identifier 'RecognizerTuple'.
Error at D:/angular2-seed/node_modules/@types/hammerjs/index.d.ts:139:15: Duplicate identifier 'HammerInput'.
Error at D:/angular2-seed/node_modules/@types/hammerjs/index.d.ts:217:15: Duplicate identifier 'MouseInput'.
Error at D:/angular2-seed/node_modules/@types/hammerjs/index.d.ts:222:15: Duplicate identifier 'PointerEventInput'.
Error at D:/angular2-seed/node_modules/@types/hammerjs/index.d.ts:227:15: Duplicate identifier 'SingleTouchInput'.
Error at D:/angular2-seed/node_modules/@types/hammerjs/index.d.ts:232:15: Duplicate identifier 'TouchInput'.
Error at D:/angular2-seed/node_modules/@types/hammerjs/index.d.ts:237:15: Duplicate identifier 'TouchMouseInput'.
Error at D:/angular2-seed/node_modules/@types/hammerjs/index.d.ts:349:15: Duplicate identifier 'TouchAction'.
    at check (D:\tools\@angular\tsc-wrapped\src\tsc.ts:43:11)
    at Tsc.typeCheck (D:\tools\@angular\tsc-wrapped\src\tsc.ts:104:5)
    at D:\tools\@angular\tsc-wrapped\src\main.ts:47:11
    at process._tickCallback (internal/process/next_tick.js:103:7)
Compilation failed
```

**Comment by albertosetim** [comment]
Same problem here!

**Comment by albertosetim** [comment]
## Proble  on run `npm run build.prod.exp`

![image](https://cloud.githubusercontent.com/assets/17254772/18954383/b0414f92-864a-11e6-902c-3ad74d9d3472.png)

## and my IDE cant find app.module.ngfactory

![image](https://cloud.githubusercontent.com/assets/17254772/18954490/4217fbd2-864b-11e6-9f54-1ee06243002d.png)

**Comment by AAAnderson7301** [comment]
@naveedahmed1 Have you found a way around this?

**Comment by JohnnyQQQQ** [comment]
Did you guys checked out https://github.com/mgechev/angular2-seed/issues/1402 ?

**Comment by naveedahmed1** [comment]
@AAAnderson7301 not yet
