### ISSUE TITLE
prod.exp failing

### ISSUE THREAD

**Issue by Marcelh29** [DeviantJS/angular2-seed-material2#72]
Don't know if its a material2 issue or seed. When building prod.exp I get the following error:

[12:28:19] Starting 'build.bundles.app.exp'...
[12:28:28] 'build.bundles.app.exp' errored after 9.1 s
[12:28:28] SyntaxError: node_modules/@angular/material/checkbox/checkbox.js: 'import' and 'export' may appear only with 'sourceType: module' (10:0)
   8 |     if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
   9 | };

**Comment by JohnnyQQQQ** [comment]
Its a known issue. It's still WIP in the seed project https://github.com/mgechev/angular-seed/issues/864

**Comment by RoxKilly** [comment]
@JohnnyQQQQ  But the seed project runs `build.bundles.app.exp` and other AoT tasks without error.

**Comment by JohnnyQQQQ** [comment]
Yes, but I won't tackle the implementation as long as it's not finalized in the seed.

**Comment by JohnnyQQQQ** [comment]
Fixed in 2f3048ba3bfa2093aecd399c6d9c59302d634cfb

**Comment by RoxKilly** [comment]
@JohnnyQQQQ  I think you will make your work easier to maintain if you add the `Material` package to `project.config.ts` instead of `seed.config.ts` since the later will change when the origin project is updated.  Here is how I added AoT compatible `Material`:

**tools/config/project.seed.ts**
```
    // add Material to SystemJS. Dev build uses the bundle. Prod uses index for AoT compatibility
    this.addPackageBundles({
      name:'@angular/material',
      path:'node_modules/@angular/material/material.umd.js',
      packageMeta:{
        main: 'index.js',
        defaultExtension: 'js'
      }
    });
```
So I didn't have to touch `seed.config.ts` at all.

**Comment by JohnnyQQQQ** [comment]
@RoxKilly good point! Somehow I get an error regarding the path: 

> Error on fetch for dist/tmp/node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory.js  

> at file:///home/johnny/Desktop/projects/javascript/angular2-seed-material2-fix/node_modules/dist/tmp/node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory.js

Did you changed something else regarding the path so that the file lookup is not relative to the node_modules dir?

**Comment by RoxKilly** [comment]
@JohnnyQQQQ  I fixed it for you one of the commits from my PR.

**Comment by felipequiroz** [comment]
Hi @RoxKilly 
I have cloned the repo and then compiled:

npm run build.dev --> OK
npm run build.prod --> OK
npm run build.prod.exp --> Error:

`[17:05:24] Starting 'compile.ahead.prod'...
Error: undefined, resolving symbol ApplicationModule in /Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/core/src/application_module.d.ts
    at simplifyInContext (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:532:15)
    at StaticReflector.simplify (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:536:20)
    at StaticReflector.annotations (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:93:28)
    at NgModuleResolver.resolve (/Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:14050:46)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:14296:49)
    at /Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:13284:43
    at Array.forEach (native)
    at _extractModulesAndPipesOrDirectives (/Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:13283:28)
    at analyzeNgModules (/Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:13039:16)
    at OfflineCompiler.compileModules (/Users/Quiroz/Development/Virtualab/iSlides/fquiroz-white-2.0/node_modules/@angular/compiler/bundles/compiler.umd.js:13115:20)
Compilation failed`

**Comment by RoxKilly** [comment]
@felipequiroz  Please don't conflate multiple issues on the same thread.

**Comment by felipequiroz** [comment]
sorry
