### ISSUE TITLE
Error happens when setting up by "npm install"

### ISSUE THREAD

**Issue by missingeverytime** [DeviantJS/angular2-seed-material2#78]
**Here is the error logs when I run "npm install" on MacOS.** 
```
[15:06:39] Starting 'print.banner'...
[15:06:40] 'print.banner' errored after 56 ms
[15:06:40] Error: Cannot find module 'supports-color'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/Users/sli/Desktop/angular_material/angular-seed/tools/tasks/seed/print.banner.ts:8:7)
    at AnonTask.run (/Users/sli/Desktop/angular_material/angular-seed/tools/utils/seed/tasks_tools.ts:31:18)
    at Gulp.<anonymous> (/Users/sli/Desktop/angular_material/angular-seed/tools/utils/seed/tasks_tools.ts:60:27)
    at module.exports (/Users/sli/Desktop/angular_material/angular-seed/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/sli/Desktop/angular_material/angular-seed/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/sli/Desktop/angular_material/angular-seed/node_modules/gulp/node_modules/orchestrator/index.js:214:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.6.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.14.22
npm ERR! code ELIFECYCLE
```
Anyone can help ?

Thanks.

**Comment by missingeverytime** [comment]
When I run "npm install" with node.js v7.0.0, it works well.

**Comment by JohnnyQQQQ** [comment]
I don't have any mac to test this. You should do a test with the original seed (https://github.com/mgechev/angular-seed) and open an issue there if you have the same bug.

Also:
 **we strongly recommend node >=v6.5.0 and npm >=3.10.3**

**Comment by missingeverytime** [comment]
Thanks for the reply...
